apiVersion: v1
kind: Service
metadata:
  name: deployment-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: webfrontend
  ports:
    - name: http
      port: 80
      targetPort: 3000