apiVersion: apps/v1
kind: Deployment
metadata:
  name: webfrontend
spec:
  selector:
    matchLabels:
      app: webfrontend
  template:
    metadata:
      labels:
        app: webfrontend
    spec:
      containers:
      - name: webfrontend
        image: chenv/ps-employee-rest-api:v1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
