apiVersion: v1
kind: Pod
metadata:
  name: webfrontend
  labels:
    name: webfrontend
spec:
  containers:
  - name: webfrontend
    image: chenv/ps-employee-rest-api:v1.0.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
